sudo: required
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
services:
  - docker
before_script:
  - docker run -p 3320:3306 --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test -d mysql:latest
  - docker run -p 3330:3306 --name mariadb -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test -d mariadb:latest
  - sleep 10
script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
